<?php
/**
 * DeadMessageFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DeadMessageFlatTest Class Doc Comment
 *
 * @category    Class
 * @description DeadMessageFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeadMessageFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeadMessageFlat"
     */
    public function testDeadMessageFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "original_message_class"
     */
    public function testPropertyOriginalMessageClass()
    {
    }

    /**
     * Test attribute "handler_class"
     */
    public function testPropertyHandlerClass()
    {
    }

    /**
     * Test attribute "encrypted"
     */
    public function testPropertyEncrypted()
    {
    }

    /**
     * Test attribute "error_count"
     */
    public function testPropertyErrorCount()
    {
    }

    /**
     * Test attribute "next_execution_time"
     */
    public function testPropertyNextExecutionTime()
    {
    }

    /**
     * Test attribute "exception"
     */
    public function testPropertyException()
    {
    }

    /**
     * Test attribute "exception_message"
     */
    public function testPropertyExceptionMessage()
    {
    }

    /**
     * Test attribute "exception_file"
     */
    public function testPropertyExceptionFile()
    {
    }

    /**
     * Test attribute "exception_line"
     */
    public function testPropertyExceptionLine()
    {
    }

    /**
     * Test attribute "scheduled_task_id"
     */
    public function testPropertyScheduledTaskId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "scheduled_task"
     */
    public function testPropertyScheduledTask()
    {
    }
}
