<?php
/**
 * OrderFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderFlatTest Class Doc Comment
 *
 * @category    Class
 * @description OrderFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderFlat"
     */
    public function testOrderFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version_id"
     */
    public function testPropertyVersionId()
    {
    }

    /**
     * Test attribute "auto_increment"
     */
    public function testPropertyAutoIncrement()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "billing_address_id"
     */
    public function testPropertyBillingAddressId()
    {
    }

    /**
     * Test attribute "billing_address_version_id"
     */
    public function testPropertyBillingAddressVersionId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "sales_channel_id"
     */
    public function testPropertySalesChannelId()
    {
    }

    /**
     * Test attribute "order_date_time"
     */
    public function testPropertyOrderDateTime()
    {
    }

    /**
     * Test attribute "order_date"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "amount_total"
     */
    public function testPropertyAmountTotal()
    {
    }

    /**
     * Test attribute "amount_net"
     */
    public function testPropertyAmountNet()
    {
    }

    /**
     * Test attribute "position_price"
     */
    public function testPropertyPositionPrice()
    {
    }

    /**
     * Test attribute "tax_status"
     */
    public function testPropertyTaxStatus()
    {
    }

    /**
     * Test attribute "shipping_costs"
     */
    public function testPropertyShippingCosts()
    {
    }

    /**
     * Test attribute "shipping_total"
     */
    public function testPropertyShippingTotal()
    {
    }

    /**
     * Test attribute "currency_factor"
     */
    public function testPropertyCurrencyFactor()
    {
    }

    /**
     * Test attribute "deep_link_code"
     */
    public function testPropertyDeepLinkCode()
    {
    }

    /**
     * Test attribute "affiliate_code"
     */
    public function testPropertyAffiliateCode()
    {
    }

    /**
     * Test attribute "campaign_code"
     */
    public function testPropertyCampaignCode()
    {
    }

    /**
     * Test attribute "state_id"
     */
    public function testPropertyStateId()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "state_machine_state"
     */
    public function testPropertyStateMachineState()
    {
    }

    /**
     * Test attribute "order_customer"
     */
    public function testPropertyOrderCustomer()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "deliveries"
     */
    public function testPropertyDeliveries()
    {
    }

    /**
     * Test attribute "line_items"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
