<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class
 * @description Product
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version_id"
     */
    public function testPropertyVersionId()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "parent_version_id"
     */
    public function testPropertyParentVersionId()
    {
    }

    /**
     * Test attribute "child_count"
     */
    public function testPropertyChildCount()
    {
    }

    /**
     * Test attribute "auto_increment"
     */
    public function testPropertyAutoIncrement()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {
    }

    /**
     * Test attribute "available_stock"
     */
    public function testPropertyAvailableStock()
    {
    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "display_group"
     */
    public function testPropertyDisplayGroup()
    {
    }

    /**
     * Test attribute "manufacturer_id"
     */
    public function testPropertyManufacturerId()
    {
    }

    /**
     * Test attribute "product_manufacturer_version_id"
     */
    public function testPropertyProductManufacturerVersionId()
    {
    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {
    }

    /**
     * Test attribute "cover_id"
     */
    public function testPropertyCoverId()
    {
    }

    /**
     * Test attribute "product_media_version_id"
     */
    public function testPropertyProductMediaVersionId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "manufacturer_number"
     */
    public function testPropertyManufacturerNumber()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "product_number"
     */
    public function testPropertyProductNumber()
    {
    }

    /**
     * Test attribute "is_closeout"
     */
    public function testPropertyIsCloseout()
    {
    }

    /**
     * Test attribute "purchase_steps"
     */
    public function testPropertyPurchaseSteps()
    {
    }

    /**
     * Test attribute "max_purchase"
     */
    public function testPropertyMaxPurchase()
    {
    }

    /**
     * Test attribute "min_purchase"
     */
    public function testPropertyMinPurchase()
    {
    }

    /**
     * Test attribute "purchase_unit"
     */
    public function testPropertyPurchaseUnit()
    {
    }

    /**
     * Test attribute "reference_unit"
     */
    public function testPropertyReferenceUnit()
    {
    }

    /**
     * Test attribute "shipping_free"
     */
    public function testPropertyShippingFree()
    {
    }

    /**
     * Test attribute "purchase_price"
     */
    public function testPropertyPurchasePrice()
    {
    }

    /**
     * Test attribute "mark_as_topseller"
     */
    public function testPropertyMarkAsTopseller()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "release_date"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "category_tree"
     */
    public function testPropertyCategoryTree()
    {
    }

    /**
     * Test attribute "property_ids"
     */
    public function testPropertyPropertyIds()
    {
    }

    /**
     * Test attribute "option_ids"
     */
    public function testPropertyOptionIds()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "listing_prices"
     */
    public function testPropertyListingPrices()
    {
    }

    /**
     * Test attribute "rating_average"
     */
    public function testPropertyRatingAverage()
    {
    }

    /**
     * Test attribute "delivery_time_id"
     */
    public function testPropertyDeliveryTimeId()
    {
    }

    /**
     * Test attribute "restock_time"
     */
    public function testPropertyRestockTime()
    {
    }

    /**
     * Test attribute "meta_description"
     */
    public function testPropertyMetaDescription()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "meta_title"
     */
    public function testPropertyMetaTitle()
    {
    }

    /**
     * Test attribute "pack_unit"
     */
    public function testPropertyPackUnit()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "calculated_price"
     */
    public function testPropertyCalculatedPrice()
    {
    }

    /**
     * Test attribute "calculated_listing_price"
     */
    public function testPropertyCalculatedListingPrice()
    {
    }

    /**
     * Test attribute "calculated_prices"
     */
    public function testPropertyCalculatedPrices()
    {
    }

    /**
     * Test attribute "calculated_max_purchase"
     */
    public function testPropertyCalculatedMaxPurchase()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "relationships"
     */
    public function testPropertyRelationships()
    {
    }
}
