<?php
/**
 * PromotionSetgroupRuleFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PromotionSetgroupRuleFlatTest Class Doc Comment
 *
 * @category    Class
 * @description PromotionSetgroupRuleFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromotionSetgroupRuleFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PromotionSetgroupRuleFlat"
     */
    public function testPromotionSetgroupRuleFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "setgroup_id"
     */
    public function testPropertySetgroupId()
    {
    }

    /**
     * Test attribute "rule_id"
     */
    public function testPropertyRuleId()
    {
    }

    /**
     * Test attribute "setgroup"
     */
    public function testPropertySetgroup()
    {
    }

    /**
     * Test attribute "rule"
     */
    public function testPropertyRule()
    {
    }
}
