<?php
/**
 * PromotionFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PromotionFlatTest Class Doc Comment
 *
 * @category    Class
 * @description PromotionFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromotionFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PromotionFlat"
     */
    public function testPromotionFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "valid_from"
     */
    public function testPropertyValidFrom()
    {
    }

    /**
     * Test attribute "valid_until"
     */
    public function testPropertyValidUntil()
    {
    }

    /**
     * Test attribute "max_redemptions_global"
     */
    public function testPropertyMaxRedemptionsGlobal()
    {
    }

    /**
     * Test attribute "max_redemptions_per_customer"
     */
    public function testPropertyMaxRedemptionsPerCustomer()
    {
    }

    /**
     * Test attribute "exclusive"
     */
    public function testPropertyExclusive()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "use_codes"
     */
    public function testPropertyUseCodes()
    {
    }

    /**
     * Test attribute "use_individual_codes"
     */
    public function testPropertyUseIndividualCodes()
    {
    }

    /**
     * Test attribute "individual_code_pattern"
     */
    public function testPropertyIndividualCodePattern()
    {
    }

    /**
     * Test attribute "use_set_groups"
     */
    public function testPropertyUseSetGroups()
    {
    }

    /**
     * Test attribute "customer_restriction"
     */
    public function testPropertyCustomerRestriction()
    {
    }

    /**
     * Test attribute "order_count"
     */
    public function testPropertyOrderCount()
    {
    }

    /**
     * Test attribute "orders_per_customer_count"
     */
    public function testPropertyOrdersPerCustomerCount()
    {
    }

    /**
     * Test attribute "exclusion_ids"
     */
    public function testPropertyExclusionIds()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "setgroups"
     */
    public function testPropertySetgroups()
    {
    }

    /**
     * Test attribute "discounts"
     */
    public function testPropertyDiscounts()
    {
    }

    /**
     * Test attribute "individual_codes"
     */
    public function testPropertyIndividualCodes()
    {
    }
}
