<?php
/**
 * SalesChannelFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesChannelFlatTest Class Doc Comment
 *
 * @category    Class
 * @description SalesChannelFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesChannelFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesChannelFlat"
     */
    public function testSalesChannelFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "customer_group_id"
     */
    public function testPropertyCustomerGroupId()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "navigation_category_id"
     */
    public function testPropertyNavigationCategoryId()
    {
    }

    /**
     * Test attribute "navigation_category_version_id"
     */
    public function testPropertyNavigationCategoryVersionId()
    {
    }

    /**
     * Test attribute "navigation_category_depth"
     */
    public function testPropertyNavigationCategoryDepth()
    {
    }

    /**
     * Test attribute "footer_category_id"
     */
    public function testPropertyFooterCategoryId()
    {
    }

    /**
     * Test attribute "footer_category_version_id"
     */
    public function testPropertyFooterCategoryVersionId()
    {
    }

    /**
     * Test attribute "service_category_id"
     */
    public function testPropertyServiceCategoryId()
    {
    }

    /**
     * Test attribute "service_category_version_id"
     */
    public function testPropertyServiceCategoryVersionId()
    {
    }

    /**
     * Test attribute "mail_header_footer_id"
     */
    public function testPropertyMailHeaderFooterId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "maintenance"
     */
    public function testPropertyMaintenance()
    {
    }

    /**
     * Test attribute "maintenance_ip_whitelist"
     */
    public function testPropertyMaintenanceIpWhitelist()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "payment_method_ids"
     */
    public function testPropertyPaymentMethodIds()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
    }

    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "shipping_methods"
     */
    public function testPropertyShippingMethods()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "customer_group"
     */
    public function testPropertyCustomerGroup()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "domains"
     */
    public function testPropertyDomains()
    {
    }

    /**
     * Test attribute "system_configs"
     */
    public function testPropertySystemConfigs()
    {
    }

    /**
     * Test attribute "navigation_category"
     */
    public function testPropertyNavigationCategory()
    {
    }

    /**
     * Test attribute "footer_category"
     */
    public function testPropertyFooterCategory()
    {
    }

    /**
     * Test attribute "service_category"
     */
    public function testPropertyServiceCategory()
    {
    }

    /**
     * Test attribute "product_visibilities"
     */
    public function testPropertyProductVisibilities()
    {
    }

    /**
     * Test attribute "mail_header_footer"
     */
    public function testPropertyMailHeaderFooter()
    {
    }

    /**
     * Test attribute "newsletter_recipients"
     */
    public function testPropertyNewsletterRecipients()
    {
    }

    /**
     * Test attribute "mail_templates"
     */
    public function testPropertyMailTemplates()
    {
    }

    /**
     * Test attribute "number_range_sales_channels"
     */
    public function testPropertyNumberRangeSalesChannels()
    {
    }

    /**
     * Test attribute "promotion_sales_channels"
     */
    public function testPropertyPromotionSalesChannels()
    {
    }

    /**
     * Test attribute "document_base_config_sales_channels"
     */
    public function testPropertyDocumentBaseConfigSalesChannels()
    {
    }

    /**
     * Test attribute "product_reviews"
     */
    public function testPropertyProductReviews()
    {
    }

    /**
     * Test attribute "seo_urls"
     */
    public function testPropertySeoUrls()
    {
    }

    /**
     * Test attribute "seo_url_templates"
     */
    public function testPropertySeoUrlTemplates()
    {
    }

    /**
     * Test attribute "main_categories"
     */
    public function testPropertyMainCategories()
    {
    }
}
