<?php
/**
 * StateMachineHistoryFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StateMachineHistoryFlatTest Class Doc Comment
 *
 * @category    Class
 * @description StateMachineHistoryFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateMachineHistoryFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateMachineHistoryFlat"
     */
    public function testStateMachineHistoryFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state_machine_id"
     */
    public function testPropertyStateMachineId()
    {
    }

    /**
     * Test attribute "entity_name"
     */
    public function testPropertyEntityName()
    {
    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {
    }

    /**
     * Test attribute "from_state_id"
     */
    public function testPropertyFromStateId()
    {
    }

    /**
     * Test attribute "to_state_id"
     */
    public function testPropertyToStateId()
    {
    }

    /**
     * Test attribute "transition_action_name"
     */
    public function testPropertyTransitionActionName()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "state_machine"
     */
    public function testPropertyStateMachine()
    {
    }

    /**
     * Test attribute "from_state_machine_state"
     */
    public function testPropertyFromStateMachineState()
    {
    }

    /**
     * Test attribute "to_state_machine_state"
     */
    public function testPropertyToStateMachineState()
    {
    }
}
