<?php
/**
 * StateMachineStateFlatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Shopware Sales-Channel API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StateMachineStateFlatTest Class Doc Comment
 *
 * @category    Class
 * @description StateMachineStateFlat
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateMachineStateFlatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateMachineStateFlat"
     */
    public function testStateMachineStateFlat()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "technical_name"
     */
    public function testPropertyTechnicalName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "state_machine_id"
     */
    public function testPropertyStateMachineId()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "translated"
     */
    public function testPropertyTranslated()
    {
    }

    /**
     * Test attribute "state_machine"
     */
    public function testPropertyStateMachine()
    {
    }

    /**
     * Test attribute "from_state_machine_transitions"
     */
    public function testPropertyFromStateMachineTransitions()
    {
    }

    /**
     * Test attribute "to_state_machine_transitions"
     */
    public function testPropertyToStateMachineTransitions()
    {
    }

    /**
     * Test attribute "order_transactions"
     */
    public function testPropertyOrderTransactions()
    {
    }

    /**
     * Test attribute "order_deliveries"
     */
    public function testPropertyOrderDeliveries()
    {
    }

    /**
     * Test attribute "orders"
     */
    public function testPropertyOrders()
    {
    }

    /**
     * Test attribute "to_state_machine_history_entries"
     */
    public function testPropertyToStateMachineHistoryEntries()
    {
    }

    /**
     * Test attribute "from_state_machine_history_entries"
     */
    public function testPropertyFromStateMachineHistoryEntries()
    {
    }
}
